# Writes html/embed-ui.js: the course's interface strings (lessons.js "ui",
# de/en/ja) without the 800 KB of lessons, for the embedded cell
# (html/embed.html). The kernel (main.rb) formats gem errors, widget labels
# and loading notes from them; the embed shows "Run", "Loading Ruby" and its
# screen-reader texts from them too. It goes stale whenever a ui string in
# lessons.js changes, so the test run checks it.
#
#   ruby tools/build_embed_ui.rb           # rewrite html/embed-ui.js
#   ruby tools/build_embed_ui.rb --check   # exit 1 if it is out of date
require "json"

HTML = File.expand_path("../html", __dir__)
LESSONS = File.join(HTML, "lessons.js")
OUT = File.join(HTML, "embed-ui.js")

# lessons.js is window.LESSONS_JSON = JSON.stringify({...}) around plain
# JSON (server/course.rb reads it the same way)
source = File.read(LESSONS, encoding: "UTF-8")
json = source[/JSON\.stringify\((.*)\);\s*\z/m, 1] or abort "#{LESSONS}: no JSON.stringify(...)"
ui = JSON.parse(json).fetch("ui")

text = "// generated by tools/build_embed_ui.rb from html/lessons.js - do not edit\n" \
       "window.CHUNKY_EMBED_UI = #{JSON.generate(ui)};\n"

if ARGV.include?("--check")
  current = File.exist?(OUT) && File.read(OUT, encoding: "UTF-8") == text
  puts current ? "current html/embed-ui.js (#{ui.keys.join(', ')})" : "STALE   html/embed-ui.js: run ruby tools/build_embed_ui.rb"
  exit(current ? 0 : 1)
end
File.write(OUT, text)
puts "wrote   html/embed-ui.js (#{ui.keys.join(', ')}, #{text.bytesize} bytes)"
